/* TODO MUTATIONS*/
export const GETLISTMUTATIONS = 'GETLISTMUTATIONS';
export const ADDLISTMUTATIONS = 'ADDLISTMUTATIONS';
export const DELLISTMUTATIONS = 'DELLISTMUTATIONS';
export const UPDATELISTMUTATIONS = 'UPDATELISTMUTATIONS';
export const FILTERMUTATIONS = 'FILTERMUTATIONS'; 

